load("//platforms:gameboy.bzl", "gameboy_rom")

gameboy_rom(
    name = "rom_1",
    srcs = [
        "main_1.c",
        "//assets:asset_src",
        "//assets:headings_src",
        "//assets:elsie_right_src",
    ],
)

gameboy_rom(
    name = "rom_2",
    srcs = [
        "main_2.c",
        "//assets:asset_src",
        "//assets:headings_src",
        "//assets:elsie_right_src",
    ],
)

gameboy_rom(
    name = "rom_3",
    srcs = [
        "main_3.c",
        "//assets:asset_src",
        "//assets:headings_src",
        "//assets:elsie_right_src",
    ],
)
