//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_elsie_hair_wave_96_128_4_H
#define METASPRITE_elsie_hair_wave_96_128_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define elsie_hair_wave_96_128_4_TILE_ORIGIN 0
#define elsie_hair_wave_96_128_4_TILE_W 8
#define elsie_hair_wave_96_128_4_TILE_H 8
#define elsie_hair_wave_96_128_4_WIDTH 96
#define elsie_hair_wave_96_128_4_HEIGHT 120
#define elsie_hair_wave_96_128_4_TILE_COUNT 139
#define elsie_hair_wave_96_128_4_PALETTE_COUNT 1
#define elsie_hair_wave_96_128_4_COLORS_PER_PALETTE 4
#define elsie_hair_wave_96_128_4_TOTAL_COLORS 4
#define elsie_hair_wave_96_128_4_MAP_ATTRIBUTES 0
extern const unsigned char elsie_hair_wave_96_128_4_map[180];
#define elsie_hair_wave_96_128_4_map_attributes elsie_hair_wave_96_128_4_map

BANKREF_EXTERN(elsie_hair_wave_96_128_4)

extern const palette_color_t elsie_hair_wave_96_128_4_palettes[4];
extern const uint8_t elsie_hair_wave_96_128_4_tiles[2224];

#endif
