//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_elsie_hair_wave_96_128_5_H
#define METASPRITE_elsie_hair_wave_96_128_5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define elsie_hair_wave_96_128_5_TILE_ORIGIN 0
#define elsie_hair_wave_96_128_5_TILE_W 8
#define elsie_hair_wave_96_128_5_TILE_H 8
#define elsie_hair_wave_96_128_5_WIDTH 96
#define elsie_hair_wave_96_128_5_HEIGHT 120
#define elsie_hair_wave_96_128_5_TILE_COUNT 140
#define elsie_hair_wave_96_128_5_PALETTE_COUNT 1
#define elsie_hair_wave_96_128_5_COLORS_PER_PALETTE 4
#define elsie_hair_wave_96_128_5_TOTAL_COLORS 4
#define elsie_hair_wave_96_128_5_MAP_ATTRIBUTES 0
extern const unsigned char elsie_hair_wave_96_128_5_map[180];
#define elsie_hair_wave_96_128_5_map_attributes elsie_hair_wave_96_128_5_map

BANKREF_EXTERN(elsie_hair_wave_96_128_5)

extern const palette_color_t elsie_hair_wave_96_128_5_palettes[4];
extern const uint8_t elsie_hair_wave_96_128_5_tiles[2240];

#endif
