//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_elsie_hair_wave_96_128_tilesheet_H
#define METASPRITE_elsie_hair_wave_96_128_tilesheet_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define elsie_hair_wave_96_128_tilesheet_TILE_ORIGIN 0
#define elsie_hair_wave_96_128_tilesheet_TILE_W 8
#define elsie_hair_wave_96_128_tilesheet_TILE_H 8
#define elsie_hair_wave_96_128_tilesheet_WIDTH 480
#define elsie_hair_wave_96_128_tilesheet_HEIGHT 128
#define elsie_hair_wave_96_128_tilesheet_TILE_COUNT 274
#define elsie_hair_wave_96_128_tilesheet_PALETTE_COUNT 1
#define elsie_hair_wave_96_128_tilesheet_COLORS_PER_PALETTE 4
#define elsie_hair_wave_96_128_tilesheet_TOTAL_COLORS 4
#define elsie_hair_wave_96_128_tilesheet_MAP_ATTRIBUTES 0
extern const unsigned char elsie_hair_wave_96_128_tilesheet_map[960];
#define elsie_hair_wave_96_128_tilesheet_map_attributes elsie_hair_wave_96_128_tilesheet_map

BANKREF_EXTERN(elsie_hair_wave_96_128_tilesheet)

extern const palette_color_t elsie_hair_wave_96_128_tilesheet_palettes[4];
extern const uint8_t elsie_hair_wave_96_128_tilesheet_tiles[4384];

#endif
