//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_elsie_right_bank_1_H
#define METASPRITE_elsie_right_bank_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define elsie_right_bank_1_TILE_ORIGIN 0
#define elsie_right_bank_1_TILE_W 8
#define elsie_right_bank_1_TILE_H 8
#define elsie_right_bank_1_WIDTH 96
#define elsie_right_bank_1_HEIGHT 120
#define elsie_right_bank_1_TILE_COUNT 140
#define elsie_right_bank_1_PALETTE_COUNT 1
#define elsie_right_bank_1_COLORS_PER_PALETTE 4
#define elsie_right_bank_1_TOTAL_COLORS 4
#define elsie_right_bank_1_MAP_ATTRIBUTES 0
extern const unsigned char elsie_right_bank_1_map[180];
#define elsie_right_bank_1_map_attributes elsie_right_bank_1_map

BANKREF_EXTERN(elsie_right_bank_1)

extern const palette_color_t elsie_right_bank_1_palettes[4];
extern const uint8_t elsie_right_bank_1_tiles[2240];

#endif
