//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_elsie_hair_wave_96_128_2_H
#define METASPRITE_elsie_hair_wave_96_128_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define elsie_hair_wave_96_128_2_TILE_ORIGIN 0
#define elsie_hair_wave_96_128_2_TILE_W 8
#define elsie_hair_wave_96_128_2_TILE_H 8
#define elsie_hair_wave_96_128_2_WIDTH 96
#define elsie_hair_wave_96_128_2_HEIGHT 120
#define elsie_hair_wave_96_128_2_TILE_COUNT 139
#define elsie_hair_wave_96_128_2_PALETTE_COUNT 1
#define elsie_hair_wave_96_128_2_COLORS_PER_PALETTE 4
#define elsie_hair_wave_96_128_2_TOTAL_COLORS 4
#define elsie_hair_wave_96_128_2_MAP_ATTRIBUTES 0
extern const unsigned char elsie_hair_wave_96_128_2_map[180];
#define elsie_hair_wave_96_128_2_map_attributes elsie_hair_wave_96_128_2_map

BANKREF_EXTERN(elsie_hair_wave_96_128_2)

extern const palette_color_t elsie_hair_wave_96_128_2_palettes[4];
extern const uint8_t elsie_hair_wave_96_128_2_tiles[2224];

#endif
