//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heading_text_1_H
#define METASPRITE_heading_text_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heading_text_1_TILE_ORIGIN 0
#define heading_text_1_TILE_W 8
#define heading_text_1_TILE_H 8
#define heading_text_1_WIDTH 160
#define heading_text_1_HEIGHT 32
#define heading_text_1_TILE_COUNT 25
#define heading_text_1_PALETTE_COUNT 1
#define heading_text_1_COLORS_PER_PALETTE 4
#define heading_text_1_TOTAL_COLORS 4
#define heading_text_1_MAP_ATTRIBUTES 0
extern const unsigned char heading_text_1_map[80];
#define heading_text_1_map_attributes heading_text_1_map

BANKREF_EXTERN(heading_text_1)

extern const palette_color_t heading_text_1_palettes[4];
extern const uint8_t heading_text_1_tiles[400];

#endif
