//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heading_text_2_H
#define METASPRITE_heading_text_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heading_text_2_TILE_ORIGIN 0
#define heading_text_2_TILE_W 8
#define heading_text_2_TILE_H 8
#define heading_text_2_WIDTH 160
#define heading_text_2_HEIGHT 32
#define heading_text_2_TILE_COUNT 31
#define heading_text_2_PALETTE_COUNT 1
#define heading_text_2_COLORS_PER_PALETTE 4
#define heading_text_2_TOTAL_COLORS 4
#define heading_text_2_MAP_ATTRIBUTES 0
extern const unsigned char heading_text_2_map[80];
#define heading_text_2_map_attributes heading_text_2_map

BANKREF_EXTERN(heading_text_2)

extern const palette_color_t heading_text_2_palettes[4];
extern const uint8_t heading_text_2_tiles[496];

#endif
