//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heading_text_3_H
#define METASPRITE_heading_text_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heading_text_3_TILE_ORIGIN 0
#define heading_text_3_TILE_W 8
#define heading_text_3_TILE_H 8
#define heading_text_3_WIDTH 160
#define heading_text_3_HEIGHT 32
#define heading_text_3_TILE_COUNT 39
#define heading_text_3_PALETTE_COUNT 1
#define heading_text_3_COLORS_PER_PALETTE 4
#define heading_text_3_TOTAL_COLORS 4
#define heading_text_3_MAP_ATTRIBUTES 0
extern const unsigned char heading_text_3_map[80];
#define heading_text_3_map_attributes heading_text_3_map

BANKREF_EXTERN(heading_text_3)

extern const palette_color_t heading_text_3_palettes[4];
extern const uint8_t heading_text_3_tiles[624];

#endif
