//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heading_text_4_H
#define METASPRITE_heading_text_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heading_text_4_TILE_ORIGIN 0
#define heading_text_4_TILE_W 8
#define heading_text_4_TILE_H 8
#define heading_text_4_WIDTH 160
#define heading_text_4_HEIGHT 32
#define heading_text_4_TILE_COUNT 33
#define heading_text_4_PALETTE_COUNT 1
#define heading_text_4_COLORS_PER_PALETTE 4
#define heading_text_4_TOTAL_COLORS 4
#define heading_text_4_MAP_ATTRIBUTES 0
extern const unsigned char heading_text_4_map[80];
#define heading_text_4_map_attributes heading_text_4_map

BANKREF_EXTERN(heading_text_4)

extern const palette_color_t heading_text_4_palettes[4];
extern const uint8_t heading_text_4_tiles[528];

#endif
