//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_numbered_tiles_H
#define METASPRITE_numbered_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define numbered_tiles_TILE_ORIGIN 0
#define numbered_tiles_TILE_W 8
#define numbered_tiles_TILE_H 8
#define numbered_tiles_WIDTH 160
#define numbered_tiles_HEIGHT 16
#define numbered_tiles_TILE_COUNT 40
#define numbered_tiles_PALETTE_COUNT 1
#define numbered_tiles_COLORS_PER_PALETTE 4
#define numbered_tiles_TOTAL_COLORS 4
#define numbered_tiles_MAP_ATTRIBUTES 0
extern const unsigned char numbered_tiles_map[40];
#define numbered_tiles_map_attributes numbered_tiles_map

BANKREF_EXTERN(numbered_tiles)

extern const palette_color_t numbered_tiles_palettes[4];
extern const uint8_t numbered_tiles_tiles[640];

#endif
